# platforms.py
# Daftar platform sosial media & situs viral (Indonesia & global)
SOCIAL_PLATFORMS = {
    # Global populer
    "Instagram": "https://instagram.com/{username}",
    "Twitter": "https://twitter.com/{username}",
    "Facebook": "https://facebook.com/{username}",
    "YouTube": "https://youtube.com/@{username}",
    "TikTok": "https://www.tiktok.com/@{username}",
    "Reddit": "https://www.reddit.com/user/{username}",
    "GitHub": "https://github.com/{username}",
    "LinkedIn": "https://www.linkedin.com/in/{username}",
    "Pinterest": "https://www.pinterest.com/{username}",
    "Twitch": "https://www.twitch.tv/{username}",
    "Snapchat": "https://www.snapchat.com/add/{username}",
    "Medium": "https://medium.com/@{username}",
    "SoundCloud": "https://soundcloud.com/{username}",
    "Vimeo": "https://vimeo.com/{username}",
    "DeviantArt": "https://deviantart.com/{username}",
    "Quora": "https://www.quora.com/profile/{username}",
    "Steam": "https://steamcommunity.com/id/{username}",
    "Dribbble": "https://dribbble.com/{username}",
    "Behance": "https://www.behance.net/{username}",
    "ProductHunt": "https://www.producthunt.com/@{username}",
    "Kaggle": "https://www.kaggle.com/{username}",
    "StackOverflow": "https://stackoverflow.com/users/{username}",
    "Flickr": "https://www.flickr.com/people/{username}",
    "WordPress": "https://{username}.wordpress.com",
    "Blogspot": "https://{username}.blogspot.com",
    "Tumblr": "https://{username}.tumblr.com",
    "Badoo": "https://badoo.com/profile/{username}",
    "VK": "https://vk.com/{username}",
    "Mixcloud": "https://www.mixcloud.com/{username}",
    "Patreon": "https://www.patreon.com/{username}",
    "BuyMeACoffee": "https://www.buymeacoffee.com/{username}",
    "Letterboxd": "https://letterboxd.com/{username}",
    "500px": "https://500px.com/{username}",
    "TripAdvisor": "https://tripadvisor.com/members/{username}",
    "Goodreads": "https://www.goodreads.com/{username}",
    "Scribd": "https://www.scribd.com/{username}",
    "Bandcamp": "https://bandcamp.com/{username}",
    "Roblox": "https://www.roblox.com/users/{username}/profile",
    "Wattpad": "https://www.wattpad.com/user/{username}",
    "Chess.com": "https://www.chess.com/member/{username}",
    "Codepen": "https://codepen.io/{username}",
    "Replit": "https://replit.com/@{username}",
    "Fiverr": "https://www.fiverr.com/{username}",
    "Upwork": "https://www.upwork.com/freelancers/~{username}",
    "Freelancer": "https://www.freelancer.com/u/{username}",
    "Canva": "https://www.canva.com/{username}",
    # Indonesia populer & viral
    "Kaskus": "https://www.kaskus.co.id/profile/{username}",
    "Kompasiana": "https://www.kompasiana.com/{username}",
    "DetikForum": "https://forum.detik.com/member.php?username={username}",
    "IDN Times": "https://community.idntimes.com/{username}",
    "Bukalapak": "https://www.bukalapak.com/u/{username}",
    "Tokopedia": "https://www.tokopedia.com/{username}",
    "Shopee": "https://shopee.co.id/{username}",
    "OLX": "https://www.olx.co.id/profile/{username}",
    "Jualo": "https://www.jualo.com/user/{username}",
    "Komikcast": "https://komikcast.com/user/{username}",
    "Mastodon.id": "https://mastodon.id/@{username}",
    "Brainly": "https://brainly.co.id/profil/{username}",
    "Zenius": "https://zenius.net/profile/{username}",
    "Ruangguru": "https://ruangguru.com/{username}",
    "CodePolitan": "https://www.codepolitan.com/{username}",
    "Dicoding": "https://www.dicoding.com/users/{username}",
    "Komunitas Bukalapak": "https://komunitas.bukalapak.com/u/{username}",
    "Indowebster": "https://forum.indowebster.com/member.php?username={username}",
    "KasKus Lounge": "https://www.kaskus.co.id/profile/{username}",
    "Viva.co.id": "https://www.viva.co.id/arsip/{username}",
    "Kompas Forum": "https://forum.kompas.com/member.php?username={username}",
    "Mamikos": "https://mamikos.com/profil/{username}",
    "Storial": "https://storial.co/{username}",
    "Qiscus": "https://qiscus.com/{username}",
    "Kumparan": "https://kumparan.com/{username}",
    "KaryaKarsa": "https://karyakarsa.com/{username}",
    "Sociabuzz": "https://sociabuzz.com/{username}",
    "IDN Media": "https://idn.media/user/{username}",
    "Hipwee": "https://www.hipwee.com/author/{username}",
    "Vidio": "https://www.vidio.com/users/{username}",
    "Blogger": "https://www.blogger.com/profile/{username}",
    # Tambahkan lebih banyak situs viral/terkenal di sini
}
